name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  windows-build:
    strategy:
      matrix:
        arch: [ x86 ]

    runs-on: windows-2019
    steps:
      - name: Checkout source
        uses: actions/checkout@v2

      - name: Get PyWebOSTV
        shell: bash
        run: |
          git clone https://github.com/supersaiyanmode/PyWebOSTV
          move /s PyWebOSTV/pywebostv egWebOS

      - name: Get ws4py
        shell: bash
        run: |
          git clone --branch "0.4.2" https://github.com/Lawouach/WebSocket-for-Python
          move /s \WebSocket-for-Python\ws4py egWebOS

      - name: pack plugin
        shell: bash
        run: |
          7z a -tzip test.egplugin ./*
          7z a -tzip test.egplugin ./egWebOS/info.py
      - name: Upload result to cache
        uses: actions/upload-artifact@v2
        with:
          name: result
#          path: ./test.egplugin
          path: ./
          retention-days: 1
