name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  windows-build:
    strategy:
      matrix:
        arch: [ x86 ]

    runs-on: windows-2019
    steps:
      - name: Checkout source
        uses: actions/checkout@v2

      - name: Get version
        id: get_version
        uses: battila7/get-version-action@v2

      - name: pack plugin
        shell: bash
        run: |
          7z a -tzip egWebOS_0.5_${{ steps.get_version.outputs.version }}.egplugin ./egWebOS
          7z a -tzip egWebOS_0.5_${{ steps.get_version.outputs.version }}.egplugin ./egWebOS/info.py

      - name: Get PyWebOSTV
        shell: bash
        run: |
          git clone https://github.com/supersaiyanmode/PyWebOSTV
          patch -d PyWebOSTV/pywebostv < pywebostv.diff
          mv PyWebOSTV/pywebostv egWebOS

      - name: Get ws4py
        shell: bash
        run: |
          git clone --branch "0.5.1" https://github.com/Lawouach/WebSocket-for-Python
          mv WebSocket-for-Python/ws4py egWebOS

      - name: pack plugin
        shell: bash
        run: |
          7z a -tzip egWebOS_0.4_${{ steps.get_version.outputs.version }}.egplugin ./egWebOS
          7z a -tzip egWebOS_0.4_${{ steps.get_version.outputs.version }}.egplugin ./egWebOS/info.py
      - name: Upload result to cache
        uses: actions/upload-artifact@v2
        with:
          name: result
          path: ./egWebOS_*
          retention-days: 1

  create-release:
    needs: [windows-build]
    runs-on: windows-2019

    steps:
      - name: Checkout source
        uses: actions/checkout@v2

      - name: Get version
        id: get_version
        uses: battila7/get-version-action@v2

      - name: Download result
        uses: actions/download-artifact@v2
        with:
          name: result

      - name: Create release
        shell: bash
        run: gh release create ${{ steps.get_version.outputs.version }} -t "WebOS connect ${{ steps.get_version.outputs.version }}" -n "New version" ./*.egplugin
        env:
        	GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
					